### ISSUE TITLE
Syntax highlighting with trailing non-alphanumeric character

### ISSUE THREAD

**Issue by tomatic** [gabrielelana/vim-markdown#26]
I think there might be a bug in the syntax highlighting. Whenever I append any kind of non-alphanumeric character to a word, syntax highlighting colors it red and underlines the word (using the xoria256 theme). This is true for !"§$%&/()=? characters and probably othes (haven't tested them all).

Additionally, seemingly random words are highlighted in the same way, e.g. in the spec/features/inline_links.md file "unescaped", "ok", "inline" and others. Is this intentional?

**Comment by gabrielelana** [comment]
I think it's the spell checker. You could either:

* Correctly set your spell language (:help spelllang) in your .vimrc (mine has set spelllang=en,it)
* Disable the spell checking for markdown files in your .vimrc with something like au FileType markdown setlocal no spell

Let me know if this works for you

**Comment by tomatic** [comment]
Bingo, it was the spell checker. Didn't even know vim one. I just turned it off by putting your second tip in my .vimrc (for future reference: it's "nospell" without the blank).

Thanks!
