### ISSUE TITLE
markdown.vim error if path contains spaces

### ISSUE THREAD

**Issue by tuantda** [gabrielelana/vim-markdown#28]
When I run gvim on windows 7, I get an error at line 64 of file `ftplugin/markdown.vim`.

Vim directory is placed in the user directory with spaces in the name and `: p` will error if there are spaces in the entire path.

After I refer in lervag/vimtex#9

I've modified the line 64 from

```VimL
execute 'setlocal dictionary+=' . expand('<sfile>:p:h:h') . '/dict/emoticons.dict'
```

to

```VimL
execute 'setlocal dictionary+=' . shellescape(expand('<sfile>:p:h:h')) . '/dict/emoticons.dict'
```

and plugin worked

You can modify this way or make some other change on your own.

Thanks!

**Comment by gabrielelana** [comment]
@tuantda thanks :wink:
