### ISSUE TITLE
allow user to disable input mangling

### ISSUE THREAD

**Issue by jclulow** [gabrielelana/vim-markdown#29]
I noticed that when I type three periods in a row, they are suddenly converted into the Unicode _HORIZONTAL ELLIPSIS_ character.  There doesn't seem to be a way to disable this, so I looked in the code and found:

```
" Replace common ascii emoticons with supported emoji
iabbrev <buffer> :-) :smile:
iabbrev <buffer> :-D :laughing:
iabbrev <buffer> :-( :disappointed:

" Replace common punctuation
iabbrev <buffer> ... …
iabbrev <buffer> << «
iabbrev <buffer> >> »
```

It would be good to provide the user the ability to opt out of this behaviour, in the same way that they can opt out of, e.g., spell checking.

**Comment by gabrielelana** [comment]
Seems fair :smile: 

Update the plugin, add `let g:markdown_enable_input_abbreviations = 0` in your `.vimrc` and you are good to do
