### ISSUE TITLE
indenting with list from insert mode loses a space

### ISSUE THREAD

**Issue by y2kbugger** [gabrielelana/vim-markdown#31]
given the cursor at position `C` and you are in Insert mode:
```
- The first bullet
- The second
- C
```

pressing tab yields:
```
- The first bullet
- The second
  -C
```

However the expected result is:
```
- The first bullet
- The second
  - C
```

Note that once manually correct to the expected result and the bullet is indent, pressing tab correctly indents further, without losing the single spaces as described above

**Comment by gabrielelana** [comment]
Nice catch, I have not ever noticed because I always use `*` for lists and with `*` it works :smile:
