### ISSUE TITLE
Table of Contents generation

### ISSUE THREAD

**Issue by ghost** [gabrielelana/vim-markdown#32]
It would be nice if this plugin could support Table of Contents generation.

Various ToC generators for markdown:
- BASH - https://github.com/ekalinin/github-markdown-toc
- Python - https://github.com/amaiorano/md-to-toc

**Comment by gabrielelana** [comment]
Maybe it would be better to have a section in the documentation with code snippet that could be put in your `.vimrc` to have this feature. I don't feel comfortable to have a feature that depends on external executables

**Comment by edvinasme** [comment]
I agree with anything that you feel comfortable with, that would allow generating ToC.
