### ISSUE TITLE
conceal support?

### ISSUE THREAD

**Issue by oblitum** [gabrielelana/vim-markdown#33]
Your plugin is the best I've found, thanks.

Would it be interesting to add vim conceal support? Personally I don't like to see bold and italic text surrounded by `*`, it's a bit of duplicated information, so I'd like to have `*` and `_` concealed instead.

**Comment by gabrielelana** [comment]
Thanks! Why not, it should be easy to do, I'll give it a try but it will be under configuration the default would stay like it is now, is this ok for you?

**Comment by oblitum** [comment]
Absolutely.

**Comment by NachiGithub** [comment]
Is there any update to this? It'd be awesome to have an option to conceal the markup chars. And yes, this is the best markdown plugin I have found so far! Thanks.

**Comment by gabrielelana** [comment]
Thanks @NachiGithub I don't have time right now but if you want to give it a shot... :wink:

**Comment by ngnmhieu** [comment]
Although not directly configured in code but I've been able to change the style of bold and italic text by changing vim terminal options (more see `:help terminal-options`):
To remove styling to words surrounded by * and _, add this line to your vimrc:
```
set t_ZH=
```
Or one could change the styling of the word by setting `t_ZH` one of the [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code)
This line set words surrounded with * or _ to green:
```
set t_ZH=^[[32m " Note ^[ is the escape sequence output by pressing ctrl-v then ESC
```

Similarly, to change bold mode use `set t_md`.
