### ISSUE TITLE
Slow file loading

### ISSUE THREAD

**Issue by ptzz** [gabrielelana/vim-markdown#36]
Is it possible to do something about the long load times for markdown files? It takes me about 3 seconds to load a 600 line file (MacBook Pro, 2.5 GHz Intel Core i5). Great plugin otherwise :+1:

**Comment by ptzz** [comment]
Cleaning my vim views folder solved the problem

**Comment by nmccready** [comment]
> Cleaning my vim views folder solved the problem

How does one do this?

**Comment by ptzz** [comment]
I’m using `vim-scripts/restore_view.vim` and it stores file configuration and postion in `~/.vim/views`. I just deleted that folder.
