### ISSUE TITLE
How can I get the same syntax color like your screenshot example?

### ISSUE THREAD

**Issue by chaozhn** [gabrielelana/vim-markdown#37]
I used Vundle install this plugin. But I can not get the same color scheme like the screenshot example. Such as: my '#' is still white instead of orange color in screenshot. What can I do? How to configure? Please help me!
This is my simple configuration for this plugin:
> au BufNewFile,BufRead *.markdown,*.mdown,*.mkd,*.mkdn,README.md  setf markdown

Thanks!

**Comment by gabrielelana** [comment]
I think it's only a matter of color scheme, try to use [mine](https://github.com/croaker/mustang-vim), to install it using Vundle put in you `~/.vimrc` the following line `Plugin 'croaker/mustang-vim'`

Just to be sure, do you have `call vundle#begin()` and `call vundle#end()` respectively before and after all the `Plugin` calls in you `~/.vimrc`?

**Comment by chaozhn** [comment]
@gabrielelana Really thank your quick reply. I just tried your color scheme, but seems no changes. I installed many plugins, is there possible conflicts between them? BTW, I use dracula.vim color schema in my **~/.vim/color**, is it override the any color scheme of plugins in **.vim/bundle**
Thanks a lot!

**Comment by gabrielelana** [comment]
@chaozhn it shouldn't, but a color scheme must be applied to take effect, did you put `colorscheme mustang` in your `~/.vimrc` or quickly you can try `:colorscheme mustang` in a markdown file and see if it works

**Comment by chaozhn** [comment]
@gabrielelana Thanks, I think I know what's wrong with my profile. By default, I use dracula.vim in my .vimrc. So either way I merge some markdown colorscheme in dracula.vim or switch manually or by detecting filetype. Anyway, I know how to do, thanks a lot!

**Comment by gabrielelana** [comment]
@chaozhn You are very welcome! :wink:
