### ISSUE TITLE
Text unreadable because of pink background

### ISSUE THREAD

**Issue by JonasPf** [gabrielelana/vim-markdown#38]
The functionality of the plugin is great, however the text is barely readable on my machine because of the pink background. Even after :syntax off it still shows the pink/red background.

This is using the standard VIM on a fresh Ubuntu 15.10 installation without any modifications:

![markdown](https://cloud.githubusercontent.com/assets/2216775/12331845/5062e82a-bae3-11e5-96fe-1d4efa18c9cb.png)

**Comment by gabrielelana** [comment]
That’s the vim spell checker. The pink background it's highlighting a spell error. You could either:

* Correctly set your spell language (:help spelllang) in your .vimrc (mine has set spelllang=en,it)
* Disable the spell checking for markdown files in your .vimrc with something like `au FileType markdown setlocal nospell`

Let me know if this works for you

**Comment by JonasPf** [comment]
Worked perfectly, thanks!
