### ISSUE TITLE
JumpToHeader should use avoid modifying search history and status

### ISSUE THREAD

**Issue by murukeshm** [gabrielelana/vim-markdown#39]
In a [Vi and Vim Stack Exchange post](http://vi.stackexchange.com/a/6074/205), @romainl posted a function to jump to headers (for mapping to `[[`, `]]`, etc.):

```viml
function! CustomJump(motion) range
    let cnt = v:count1
    let save = @/
    mark '
    while cnt > 0
        silent! execute a:motion
        let cnt = cnt - 1
    endwhile
    call histdel('/', -1)
    let @/ = save
endfunction
```

While I prefer the current [`s:JumpToHeader()`](https://github.com/gabrielelana/vim-markdown/blob/master/ftplugin/markdown.vim#L95), I feel it could be improved to avoid modifying search history:

```viml
function! s:JumpToHeader(forward, visual)
  let save = @/
  let pattern = '\v^#{1,6}.*$|^.+\n%(\-+|\=+)$' 
  " snip  
  execute 'silent normal! ' . direction . pattern . "\n"
  call histdel('/', -1)
  let @/ = save
endfunction
```

Another useful bit would the `while` loop, which lets @romainl's mapping respect a count.

**Comment by gabrielelana** [comment]
@murukeshm nice! What about a pull request?
