### ISSUE TITLE
E363: pattern uses more memory than 'maxmempattern'

### ISSUE THREAD

**Issue by ander2** [gabrielelana/vim-markdown#4]
Hi,
I've just downloaded (with Pathogen) and tried the plugin and this error is raised every time I open a *.md file. 
What's going on?

**Comment by sam3k** [comment]
@gabrielelana what's this annoying strategy you speak of? Could use it myself. =)

**Comment by sam3k** [comment]
Actually, this `E363: pattern uses more memory than 'maxmempattern'` went away after I installed vim-javascript; which I didn't realize I had to have. Using VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
