### ISSUE TITLE
New list items not being generated on pressing 'enter'

### ISSUE THREAD

**Issue by ManiacalAce** [gabrielelana/vim-markdown#47]
I recently updated my plugins and something seems to have broken.

Before, in a list, when pressing 'enter', the next list item would already be generated. For example, the cursor would be here
```
- Item 1
- |
```

Now, when I press 'enter', I end up with no new list item and just some indentation:

```
- Item 1
  |
```

I don't know vimscript so can't look into details, but think that this commit broke things:
eed4058. Things work fine on the commit before that.

**Comment by gabrielelana** [comment]
@ManiacalAce I found a solution that hopefully will make everyone happy, update and try ;-)
