### ISSUE TITLE
RMarkdown integration

### ISSUE THREAD

**Issue by diegodiazd** [gabrielelana/vim-markdown#48]
Hi,

Very useful tool, thanks. Just a short question. Is it possible to edit R chunks from **Rmarkdown** / **Swave** files as markdown code blocks?. The syntax is slightly different, for example:

\`\`\`\{r, echo=FALSE}
Some R code
\`\`\`
When I type \<Leader\>e  over the chunk above I've got just the current line written in the tmp file, instead of the entire chunk. Besides, the tmp file is parsed as markdown file, instead of R file.

Thanks in advance.

Diego.

**Comment by gabrielelana** [comment]
@diegodiazd now it should work 😄

**Comment by diegodiazd** [comment]
Thanks @gabrielelana :). R blocks from Rmarkdown/Sweave work perfectly. Just a little detail although. In regular markdown blocks, the syntax is not loaded in the tmp file. For instance:

\`\`\`python
print "hello world"
\`\`\`
is opened as a regular markdown, not as a python file.

**Comment by gabrielelana** [comment]
@diegodiazd Thanks!  It's a regression, I don't have automatic tests for this feature (too complex), fixed with 21fbfe1bb1a182f88146f76a426b17a976be96b2

**Comment by diegodiazd** [comment]
Thanks @gabrielelana ;)
