### ISSUE TITLE
Folding for lists

### ISSUE THREAD

**Issue by mkollaro** [gabrielelana/vim-markdown#50]
The docs says "Folding for: headers, code blocks, html blocks and lists", yet I don't see any folds for the list, only the headings. Is it still WIP or am I doing something wrong?

I did set `let g:markdown_enable_folding = 1` and  tried a text similar to the example in the README.

I would like folds that would create something like:

```
# h1 {{{1
* asdf {{{2
    * qwerty {{{3
* foo {{{2
```

**Comment by gabrielelana** [comment]
> The docs says "Folding for: headers, code blocks, html blocks and lists", yet I don't see any folds for the list, only the headings. Is it still WIP or am I doing something wrong?

Nothing wrong, I worked on it for a while, then I found it almost unusable: wrong some of the time and terribly slow. I will update the documentation until a find a better way to do it
