### ISSUE TITLE
Utilize vim conceal feature to achieve a higher readibility

### ISSUE THREAD

**Issue by tamlok** [gabrielelana/vim-markdown#54]
Hi, thanks for your nice work! What do you think if we could utilize vim's conceal feature to hide some markers?
For example,
1. \`abcd\`, we could just display "abcd" in a highlighted mode;
2. \*ancd\* and \*\*abcd\*\*, we could just display "abcd" in italic or bold mode;

Thanks very much!

**Comment by gabrielelana** [comment]
Hi, thanks for the suggestion, I don't have anything against the concealing but I'm not a bit fan either

We can put the concealing under a configuration flag and that would be awesome

I don't have time right now to do it but pull requests are welcome 😄

**Comment by tamlok** [comment]
Already publish a pull request! Just utilize conceal for italic, bold, bolditalic, inline-code and link.
