### ISSUE TITLE
Highlighting Two Trailing Blanks

### ISSUE THREAD

**Issue by StaticNoiseLog** [gabrielelana/vim-markdown#57]
It would be nice if there was a way to highlight two trailing blanks on a line. This is the way to enforce a new line within the same paragraph (break line). Tim Pope's markdown.vim does it correctly and I find this very useful.

**Comment by srsudar** [comment]
I get this by using [ntpeters/vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace).

**Comment by srsudar** [comment]
Well I take it back. It works in file types other than markdown. If I get it fixed I'll report back. I'm finding this plugin to be pretty opinionated about the settings it overrides...

**Comment by StaticNoiseLog** [comment]
Thanks for looking into it!

**Comment by srsudar** [comment]
Got it. My criticism of opinionated setting overrides was misplaced on this one. The [ntpeters/vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace) plugin has markdown blacklisted by default.

I now have trailing spaces with that plugin installed and the following in my `.vimrc` (this is the default minus markdown):

```
let g:better_whitespace_filetypes_blacklist=['diff', 'gitcommit', 'unite', 'qf', 'help']
```

**Comment by StaticNoiseLog** [comment]
Awesome!
